### ISSUE TITLE
Is it possible to highlight the keywords?

### ISSUE THREAD

**Issue by hellt** [tomi/vscode-rf-language-server#3]
Wondering if this is possible? Would make my test suites much more readable...

**Comment by tomi** [comment]
Hi! I think it should be doable. I'll investigate this.

**Comment by srexperts** [comment]
I would love to see the syntax highlighting as seen on the official RF site:
![image](https://cloud.githubusercontent.com/assets/26834608/24586475/80a2ddb8-17aa-11e7-962c-85a90da59872.png)
It has all the keywords/params/vars highlighted in a meaningful name

Because what I have now is a bit clumsy, keywords are not visually detached from named arguments, what makes it difficult to read for a non-robot person
![image](https://cloud.githubusercontent.com/assets/26834608/24586494/0af3d274-17ab-11e7-808c-54548c593a0e.png)

**Comment by tomi** [comment]
I completely agree that the syntax highlighting is a bit limited for the moment. Thanks for providing that image for reference, that is what we should aim for.

**Comment by tomi** [comment]
Hi! I just released version 0.5.1 which has much more powerful syntax highlighting. Please give it a try and let me know if it's missing anything!

**Comment by hellt** [comment]
Thanks @tomi for quickly responding to that request! Awesome work, though I think some things we might improve.
Lets see how different themes react to the following boilerplate
```
*** Test Cases ***
# Testing Comment
Sample Test Name
    [Documentation]    Example test
    [Setup]    Open Application    App B
    [Arguments]    ${path}
    [Tags]    owner-mrx    not_ready
    ${return}=Keyword Name    ${org_admin}  # unnamed variable
    ...                       scalar value  # scalar value as positional arg
    ...                       password=cats  # named arg with scalar
    ...                       cats_org_name=${org_name}  # named arg with variable assigned
    ...                       cats_reuse=true            # boolean type
    [Teardown]    NONE
```
[**Ayu Dark/Light**](https://marketplace.visualstudio.com/items?itemName=teabyii.ayu)
![image](https://cloud.githubusercontent.com/assets/5679861/24691662/9b548258-19dd-11e7-8379-87b7e8f8523c.png)
![image](https://cloud.githubusercontent.com/assets/5679861/24691669/a96e1e44-19dd-11e7-8519-2bc63299b2c6.png)
1. Does it make sense to color differently `${}` and the name of the var inside it? Kinda overcolored?
2. Seems like `[Arguments]` control world has different color scheme from [Documentation] and Teardowns
3. Its hard to distinct named variable from its value. Take a look at `password=cats` parameter. Maybe we should color the named args somehow? Or color the variable value?
4. Seems like its related to this theme, but `*** Test Cases ***` control world has a color in the same pallete as scalars and named variables

[**Material**](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Theme-MaterialKit)
![image](https://cloud.githubusercontent.com/assets/5679861/24691913/fe164dee-19de-11e7-8964-10e302949144.png)
Same comments for this theme

[**Sublime Material Theme**](https://marketplace.visualstudio.com/items?itemName=jprestidge.theme-material-theme)
![image](https://cloud.githubusercontent.com/assets/5679861/24692098/001e7818-19e0-11e7-899f-dcc4d9935a31.png)
I thought that my favorite Ayu theme was the only one with an issue that `*** Test Case ***` control world has the same problem of the same (or almost the same) color as test name

**Comment by tomi** [comment]
1. I was aiming for the same highlighting as RF has on their [examples page](http://robotframework.org/#examples). I agree that it's a bit confusing now. I'll see if a more neutral colour would work, like `...` has.
2. Yes this seems to be a bug. Need to fix this.
3. I agree. They should have a different groups.
4. Hmmm this is odd.. It has a different colour on my machine with Material theme:

![screen shot 2017-04-05 at 20 26 33](https://cloud.githubusercontent.com/assets/10324676/24718307/350094e0-1a3e-11e7-8a3f-1f84201d947e.png)

**Comment by hellt** [comment]
Thanks for 0.6.1 release
Now it looks quite good. Still cant say if the different color for `${}` symbols and the name of the variable looks harmonized
![image](https://cloud.githubusercontent.com/assets/5679861/24945889/af43f5f0-1f69-11e7-9ee7-69058b554739.png)

light one:
![image](https://cloud.githubusercontent.com/assets/5679861/24945916/c86dda3c-1f69-11e7-9803-5fa58a394c51.png)

**Comment by hellt** [comment]
KW Highlighting is lost when doing variables assign by KW return value
![image](https://cloud.githubusercontent.com/assets/5679861/25303680/b38bfc76-2760-11e7-8ef5-c1a32d0e2df8.png)
